name: blavapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.2+11

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.8.5
  curved_navigation_bar: ^1.0.3
  diacritic: ^0.1.3
  equatable: ^2.0.3
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  firebase_storage: ^11.2.6
  flare_flutter: ^3.0.2
  flex_color_scheme: ^7.3.1
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^15.1.0+1
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.0
  flutter_swipe_detector: ^2.0.0
  fluttertoast: ^8.0.9
  google_fonts: ^5.1.0
  image_picker: ^1.0.2
  implicitly_animated_reorderable_list: ^0.4.2
  json_annotation: ^4.8.1
  json_serializable: ^6.3.1
  maps_launcher: ^2.0.1
  mobile_scanner: ^3.4.1
  qr_flutter: ^4.0.0
  rive: ^0.11.14
  share_plus: ^7.1.0
  shared_preferences: ^2.0.13
  syncfusion_flutter_calendar: ^22.2.9
  url_launcher: ^6.1.5
dependency_overrides:
  image_picker_android: 0.8.5+2

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: null
  flutter_gen_runner: null
  flutter_launcher_icons: null
  flutter_lints: ^2.0.1
  flutter_native_splash: null
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/catering/
    - assets/icons/programme/
    - assets/maps/
    - assets/flare/
    - assets/rive/

# flutter packages pub run build_runner build
flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
  assets:
    enabled: true
    package_parameter_enabled: false
    style: dot-delimiter
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs: []

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/launcher.png
  adaptive_icon_foreground: assets/launcher.png
  adaptive_icon_background: "#8D7F7D"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#8D7F7D"
  image: assets/launcher.png
  android: true
  ios: true
  web: true
  android12: true
